### PR TITLE
Terminal driver with text areas

### PR DESCRIPTION
**Pull request by gegy1000**
This PR implements a terminal driver, supporting text areas, which are dedicated areas on the screen where text can be written to.

I am unsure of the design of this, so I'd love feedback.

### CODE REVIEW

**Comment by Restioson** [comment]
Look mostly good! However, just as an aside - how much of these traits could be implemented automatically?

**Comment by gegy1000** [comment]
@Restioson What do you mean by this? How could these traits be automatically implemented?

**Comment by Restioson** [comment]
Traits can have methods with default implementations. E.g
```rust
trait A {
    fn do_something_required();
    fn do_something_auto_impl() {
        for i in 0..4 {
            Self::do_something_required();
        }
    }
}
```

For instance, perhaps `set_char` or whatever could be required, but everything else could be automatically implemented? We should just keep auto implementations in mind to avoid verbosity.

**Comment by gegy1000** [comment]
Closing to redesign.

**Pull request closed without merging**
