### PR TITLE
Implement polling PS/2 driver

### PR DESCRIPTION
**Pull request by gegy1000**
This PR implements a polling based PS/2 driver, allowing both mouse and keyboard input.

### CODE REVIEW

**Comment by Restioson** [comment]
Merge conflict

**Comment by Restioson** [comment]
Has unused warnings -- please fix or `#[allow(dead_code)]` (when doing this please leave a comment why)

**Comment by Restioson** [comment]
I thought this let mouse and keyboard input through the same device, too? Would this be considered 'broken'?

**Comment by gegy1000** [comment]
Nope, that's dependent on how you read from the devices. It'd be broken on the keyboard end if it read wrong.

**Comment by Restioson** [comment]
Ok, cool. Could you fix the warnings?

**Comment by Restioson** [comment]
Yeah, I'm going to go out on a limb and say this maybe is a bug? 😂 https://i.imgur.com/X2rKLPv.png

**Comment by gegy1000** [comment]
@Restioson This branch doesn't have the vga fixes merged. Unrelated.

**Comment by Restioson** [comment]
Oh, sure. Merging

**Pull request merged**
